# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'syncthing::syncthing_bcrypt') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    begin
      require 'bcrypt'
    rescue LoadError
      raise Puppet::ParseError, "syncthing_bcrypt(): bcrypt gem is required to hash passwords."
    end

    if args.length == 1
      BCrypt::Password.create(args[0]).to_s
    elsif args.length == 2
      # Custom salt.
      BCrypt::Engine.hash_secret args[0], args[1]
    else
      raise Puppet::ParseError, "syncthing_bcrypt(): Invalid number of arguments."
    end
  
  end
end
